// 这个文件已经全部加上中文注释
/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.spark.storage

import org.apache.spark.SparkException
import org.apache.spark.storage.LogBlockType.LogBlockType

/**
 * LogBlockIdGenerator 负责为日志块生成唯一的 LogBlockId
 */
trait LogBlockIdGenerator {
  // 该生成器支持的日志块类型
  def logBlockType: LogBlockType

  // 基于最后日志时间和 executor ID 生成唯一的 LogBlockId
  protected def genUniqueBlockId(lastLogTime: Long, executorId: String): LogBlockId

  /**
   * 基于最后日志时间和 executor ID 生成新的 LogBlockId。
   * 确保生成的 LogBlockId 的日志块类型与该生成器的类型一致。
   *
   * @param lastLogTime 最后日志条目的时间戳
   * @param executorId 生成日志块的 executor ID
   */
  final def nextBlockId(lastLogTime: Long, executorId: String): LogBlockId = {
    val blockId = genUniqueBlockId(lastLogTime, executorId)
    if (blockId.logBlockType != this.logBlockType) {
      throw SparkException.internalError(
        "BlockId generated by LogBlockIdGenerator does not match " +
        s"the expected log block type: ${blockId.logBlockType} != ${this.logBlockType}")
    }
    blockId
  }
}

// Python Worker 日志块 ID 生成器
class PythonWorkerLogBlockIdGenerator(
    sessionId: String,
    workerId: String)
  extends LogBlockIdGenerator {

  override def logBlockType: LogBlockType = LogBlockType.PYTHON_WORKER

  override protected def genUniqueBlockId(lastLogTime: Long, executorId: String): LogBlockId =
    PythonWorkerLogBlockId(lastLogTime, executorId, sessionId, workerId)
}
